version: 2
defaults: &defaults
  working_directory: /ionic-docs
  docker:
    - image: node:10
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          # -vNUM is a version toggle for busting cache
          key: node_modules_{{ checksum "package.json" }}-v0
      - run:
          name: Install node modules
          command: npm i
      - save_cache:
          # Must mach number above
          key: node_modules_{{ checksum "package.json" }}-v0
          paths:
          - ~/ionic/node_modules/
      - persist_to_workspace:
          root: /ionic-docs
          paths:
            - "*"

  framework:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /ionic-docs
      - restore_cache:
          key: api-v0
      # Generate Docs for each section concurrently
      - run:
          name: Generate Framework Docs
          no_output_timeout: 20m
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                npm run docgen framework
              else
                echo "We are on ${CIRCLE_BRANCH} branch, not going to update docs."
              fi
      - save_cache:
          key: api-v0
          paths:
            - sources/ionic/

  cli:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /ionic-docs
      - restore_cache:
          key: cli-v0
      # Generate Docs for each section concurrently
      - run:
          name: Generate CLI Docs
          no_output_timeout: 20m
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                npm run docgen cli
              else
                echo "We are on ${CIRCLE_BRANCH} branch, not going to update docs."
              fi
      - save_cache:
          key: cli-v0
          paths:
            - sources/ionic-cli/

  component-preview:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /ionic-docs
      - restore_cache:
          key: component-preview-v0
      # Generate Docs for each section concurrently
      - run:
          name: Generate Component Preview Docs
          no_output_timeout: 20m
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                npm run docgen component
              else
                echo "We are on ${CIRCLE_BRANCH} branch, not going to update docs."
              fi
      - save_cache:
          key: component-preview-v0
          paths:
            - sources/component-preview/

  native:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /ionic-docs
      - restore_cache:
          key: native-v0
      # Generate Docs for each section concurrently
      - run:
          name: Generate Component Preview Docs
          no_output_timeout: 20m
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                npm run docgen native
              else
                echo "We are on ${CIRCLE_BRANCH} branch, not going to update docs."
              fi
      - save_cache:
          key: native-v0
          paths:
            - sources/ionic-native/

  storage:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /ionic-docs
      - restore_cache:
          key: storage-v0
      # Generate Docs for each section concurrently
      - run:
          name: Generate Component Preview Docs
          no_output_timeout: 20m
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                npm run docgen storage
              else
                echo "We are on ${CIRCLE_BRANCH} branch, not going to update docs."
              fi
      - save_cache:
          key: storage-v0
          paths:
            - sources/ionic-storage/